### ISSUE TITLE
after update - collect_stats won't work

### ISSUE THREAD

**Issue by drfm** [ohld/igbot#279]
After I updated the files, I git this error while trying to collect the stats...

Traceback (most recent call last):
  File "instabot/examples/collect_stats.py", line 31, in <module>
    bot.save_user_stats(args.user, path=args.path)
  File "C:\Python36\lib\site-packages\instabot\bot\bot.py", line 384, in save_user_stats
    return save_user_stats(self, username, path=path)
  File "C:\Python36\lib\site-packages\instabot\bot\bot_stats.py", line 45, in save_user_stats
    self.logger.info("Stats saved at %s." % data_to_save["date"])
UnboundLocalError: local variable 'data_to_save' referenced before assignment
2017-07-13 19:16:24,852 - INFO - Bot stopped. Worked: 1 day, 19:09:21.593086
2017-07-13 19:16:24,853 - INFO - Total followed: 150
2017-07-13 19:16:24,855 - INFO - Total requests: 9592

**Comment by sudoguy** [comment]
In update https://github.com/instagrambot/instabot/commit/1bba82b2d109cecdb4588f35f2da7778a1fd7823 this problem was solved

**Comment by drfm** [comment]
Thanks!!!

**Comment by mwargan** [comment]
@sudoguy Hey! I still get this same error even with the update...

Interestingly - ultimate_schedule is working fine and saving stats as expected, so I updated this line in collect_stats.py:

`bot.save_user_stats(args.user, path=args.path)` 
 to
`bot.save_user_stats(bot.user_id)`, and now stats are saved.
