### ISSUE TITLE
unfollow_delay doesn't work in ultimate schedule

### ISSUE THREAD

**Issue by angeloiaia** [ohld/igbot#362]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

#-*- coding: utf-8 -*-
import schedule
import time
import sys
import os
import random
from tqdm import tqdm
import threading        #->added to make multithreadening possible -> see fn run_threaded

sys.path.append(os.path.join(sys.path[0],'../../'))
from instabot import Bot
bot = Bot(
			filter_users=False,
			**unfollow_delay=30,**
			comments_file="comments.txt", 
			blacklist="blacklist.txt"
)

bot.login(username="example", password="example")
bot.logger.info("ULTIMATE script. 24hours save")

#--- FILE TXT ---
random_hashtag_file = bot.read_list_from_file("hashtag_database.txt")
random_user_file = bot.read_list_from_file("username_database.txt")
comments_file_name = "comments.txt"

#fn to return random value for separate jobs
def get_random(from_list):
    _random=random.choice(from_list)
    print("Random from ultimate.py script is chosen: \n" + _random + "\n")
    return _random

#--- JOBS ---
**def job3(): bot.unfollow_non_followers()**
			
#function to make threads
def run_threaded(job_fn):
    job_thread=threading.Thread(target=job_fn)
    job_thread.start()

#UNFOLLOW
**schedule.every(1).days.at("14:15").do(run_threaded, job3)**

while True:
    schedule.run_pending()
    time.sleep(1)

Error/Debug Log:
![4](https://user-images.githubusercontent.com/32001281/31584847-0d1f8de4-b1b7-11e7-87e7-fa0114d7d03a.PNG)
![5](https://user-images.githubusercontent.com/32001281/31584846-0d02c48e-b1b7-11e7-92ca-b4dabe03c56a.PNG)
---

### Describe your issue

Hello,
I'm configuring the ultimate.py script in the ultimate_schedule folder.
I set the unfollow_delay parameter in Bot (). 
**When I start the script, it begins to remove the followers very quickly. 
Looking at my account nothing happens, no follower has been removed.**

_PS. Obviously the script also performs other jobs that I removed to avoid confusion._

**Comment by ohld** [comment]
Please @sudoguy and @damirqa help him with that issue. It is important.

**Comment by sudoguy** [comment]
@angeloiaia thanks for issue! This bug was fixed in last commit (https://github.com/instagrambot/instabot/commit/4aaddbace84a4308ed99139a38153585d25bf92d)

**Comment by angeloiaia** [comment]
I updated everything by typing **pip install -U instabot**, but it still does not work.
